// Prefix for screen IDs
const SCREEN_PREFIX = "rn.app.01.";

// Screen IDs
export const AUTH_SCREEN = SCREEN_PREFIX + "AUTH_SCREEN";
export const FIND_PLACE_SCREEN = SCREEN_PREFIX + "FIND_PLACE_SCREEN";
export const ADD_PLACE_SCREEN = SCREEN_PREFIX + "ADD_PLACE_SCREEN";
export const VIEW_PLACE_SCREEN = SCREEN_PREFIX + "VIEW_PLACE_SCREEN";
export const SIDE_DRAWER_SCREEN = SCREEN_PREFIX + "SIDE_DRAWER_SCREEN";
